// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQrwU7tjLzay1qJBH8Myx9g8yFhtHYfgI',
    appId: '1:1034458032882:web:d4921d07e3541f63f7fe6b',
    messagingSenderId: '1034458032882',
    projectId: 'tracttravel',
    authDomain: 'tracttravel.firebaseapp.com',
    storageBucket: 'tracttravel.appspot.com',
    measurementId: 'G-S972P3JF9K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUmv8sbEPeT1SeEUP1TF5LaIpkl0Vd1Ls',
    appId: '1:1034458032882:android:8af7a2737118c15df7fe6b',
    messagingSenderId: '1034458032882',
    projectId: 'tracttravel',
    storageBucket: 'tracttravel.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdxEoNDEpxqRHSSMsId7tHURGmyAoKatM',
    appId: '1:1034458032882:ios:9bc8a657365df26df7fe6b',
    messagingSenderId: '1034458032882',
    projectId: 'tracttravel',
    storageBucket: 'tracttravel.appspot.com',
    iosBundleId: 'com.example.tract',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdxEoNDEpxqRHSSMsId7tHURGmyAoKatM',
    appId: '1:1034458032882:ios:9bc8a657365df26df7fe6b',
    messagingSenderId: '1034458032882',
    projectId: 'tracttravel',
    storageBucket: 'tracttravel.appspot.com',
    iosBundleId: 'com.example.tract',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQrwU7tjLzay1qJBH8Myx9g8yFhtHYfgI',
    appId: '1:1034458032882:web:f9968b0c4e70adfff7fe6b',
    messagingSenderId: '1034458032882',
    projectId: 'tracttravel',
    authDomain: 'tracttravel.firebaseapp.com',
    storageBucket: 'tracttravel.appspot.com',
    measurementId: 'G-XMRDLWJ1YB',
  );
}
